### ISSUE TITLE
undefined symbol: _ZNK2cv9Feature2D5emptyEv

### ISSUE THREAD

**Issue by colegleason** [hulop/SfMLocalization#8]
@tatsuya-ishihara I've been trying to add some new endpoints to the node server but I somehow screwed something up. Have you seen anything similar to the following error?

```
Error: /home/cmaccess/SfMLocalization/VisionLocalizeServer/build/Release/localizeImage.node: undefined symbol: _ZNK2cv9Feature2D5emptyEv
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/cmaccess/SfMLocalization/VisionLocalizeServer/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/cmaccess/SfMLocalization/VisionLocalizeServer/routes/localize.js:28:37)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by tatsuya-ishihara** [comment]
What do you mean add new endpoints?
Is this build error or runtime error of node.js?

**Comment by colegleason** [comment]
I'm just trying to add new functionality to the localization engine in the server.

This is a runtime error when loading the node addon.

**Comment by tatsuya-ishihara** [comment]
Did you add new cpp file? If you add new file, please update binding.gyp.

**Comment by colegleason** [comment]
No, the problem seemed to be that I somehow installed OpenCV 2.4 into `/usr/local/libs` so it was overriding OpenCV 3.0 in `/opt`. I also had to add `-lglog` to the libraries.

**Comment by tatsuya-ishihara** [comment]
OK. I'm not sure about glog, but we uses OpenCV 3.0 functions. Please use OpenCV 3.0.
